feat: Require NEAR regular RPC URL additionally in configs
near/read-rpc pull request #137
Opened 2023-11-20 17:05 UTC by kobayurii

2023-11-20 17:05 UTC, kobayurii commented
https://github.com/near/read-rpc/issues/136

2023-11-21 08:45 UTC, khorolets requested changes
Looks good! Please, improve the naming, it's not "archive" but "archival"

2023-11-21 08:45 UTC, khorolets commented on rpc-server/src/config.rs
> +    #[clap(long, env = "ARCHIVE_NEAR_RPC_URL")]
`ARCHIVAL_NEAR_RPC_URL` please

2023-11-21 08:45 UTC, khorolets commented on rpc-server/src/config.rs
> +    pub archive_rpc_url: Option<http::Uri>,
```suggestion
    pub archival_rpc_url: Option<http::Uri>,
```

2023-11-21 08:45 UTC, khorolets commented on rpc-server/src/modules/queries/methods.rs
> +                // We can calculate the proof for state only on archive nodes.
This comment is not true. We can calculate proofs on regular nodes as well. What we cannot do is we cannot calculate it on ReadRPC.

Put a TODO here, please. Ideally, we would like to differentiate regular-data requests from the historical ones and proxy such requests to a corresponding NEAR RPC URL, but for now, let's proxy all such requests to the Archival node.

2023-11-21 08:45 UTC, khorolets commented on rpc-server/src/utils.rs
> +pub struct JsonRpcClient {
Doc-string explaining this would be nice for future us.

2023-11-21 09:35 UTC, khorolets requested changes

2023-11-21 09:35 UTC, khorolets commented on rpc-server/src/modules/queries/methods.rs
> +                // we will be able to separate proxies queries to regular and archive nodes.
```suggestion
                // we will be able to separate proxies queries to regular and archival nodes.
```

2023-11-21 09:35 UTC, khorolets commented on rpc-server/src/modules/queries/methods.rs
> +                // For now we will proxy all requests with `include_proof` to archive nodes.
```suggestion
                // For now we will proxy all requests with `include_proof` to archival nodes.
```

2023-11-21 09:35 UTC, khorolets commented on rpc-server/src/utils.rs
> +    archive_client: near_jsonrpc_client::JsonRpcClient,
```suggestion
    archival_client: near_jsonrpc_client::JsonRpcClient,
```

2023-11-21 09:35 UTC, khorolets commented on rpc-server/src/utils.rs
> +    pub async fn archive_call<M>(
```suggestion
    pub async fn archival_call<M>(
```

2023-11-21 10:06 UTC, khorolets submitted a review, later dismissed

2023-11-21 10:13 UTC, khorolets approved these changes

2023-11-21 10:18 UTC, merged