Implement support for optimistic block finality
near/read-rpc pull request #197
Opened 2024-03-07 18:44 UTC by kobayurii

2024-03-07 20:00 UTC, kobayurii commented
https://github.com/near/read-rpc/issues/186

2024-03-11 14:28 UTC, khorolets requested changes
👍 Looks great! We agreed about some fixes and corrections to be done

2024-03-11 14:28 UTC, khorolets commented on rpc-server/src/modules/blocks/mod.rs
> +                shards: vec![],
Please leave a comment explaining why it is empty here.

2024-03-11 14:28 UTC, khorolets commented on rpc-server/src/modules/blocks/mod.rs
> +    pub async fn account_changes_in_block(
Please leave doc-strings explaining the reasoning behind these methods here.

2024-03-11 14:28 UTC, khorolets commented on rpc-server/src/modules/queries/methods.rs
> +    if let Ok(result) = data
Put a comment explaining the logic of relying on the Err for non-optimistic queries for future us.

2024-03-11 14:28 UTC, khorolets commented on rpc-server/src/modules/queries/methods.rs
> +    if let Ok(result) = data
Or break down so different functions as discussed on the call

2024-03-11 14:28 UTC, khorolets commented on rpc-server/src/modules/queries/methods.rs
> +    let optimistic_data = data
If I requested Final, this piece anyway will return me optimistic.

2024-03-11 14:28 UTC, khorolets commented on rpc-server/src/modules/queries/utils.rs
> +    if state_from_db.is_empty() && optimistic_data.is_empty() {
I wouldn't say I like the idea of putting this logic here. I agree to have it here for now but consider adding a TODO to refactor it later.

2024-03-12 09:49 UTC, khorolets approved these changes
Looks good enough for me! Let's start planning the roll-up 👍

2024-03-12 09:51 UTC, merged