feat: added `view_receipt_record` rpc endpoint
near/read-rpc pull request #266
Opened 2024-05-31 18:51 UTC by frolvanya

Here's an example of calling `view_receipt_record`:
<img width="1063" alt="image" src="https://github.com/near/read-rpc/assets/59515280/6209422d-e152-44e9-a482-c0bb23949647">

closes #264

2024-06-01 07:53 UTC, khorolets requested changes
Nice job indeed! I left a few change requests, but please wait for @kobayurii review before rushing on it. Thank!

2024-06-01 07:53 UTC, khorolets commented on rpc-server/src/modules/receipts/methods.rs
> +            data.near_rpc_client.clone(),
The entire shadow data consistency check is redundant here. There is no such method on native RPC, so there is nothing to compare. Please drop it.

2024-06-01 07:53 UTC, khorolets commented on rpc-server/src/modules/receipts/methods.rs
> +            println!("Error in `fetch_receipt_record` call: {:?}", err);
leftover print

2024-06-01 07:53 UTC, khorolets commented on rpc-server/src/metrics.rs
> +    pub static ref RECEIPT_RECORD_REQUESTS_TOTAL: IntCounter = try_create_int_counter(
We have migrated to the common total counter with labels, I believe @kobayurii made a middleware for it.

I will let him to elaborate on that

2024-06-01 13:47 UTC, frolvanya commented
Thanks for a review! I guess I need to pay more attention to delete all debug leftovers. I've fixed first two issues and I'll wait for @kobayurii review, before pushing changes. However, I still don't know if it's fine to return non Response type from RPC endpoint. Can someone tell me if it's a good practice:
https://github.com/near/read-rpc/blob/ac8f4f221afe391c20144cd7c7397868d13a525c/readnode-primitives/src/lib.rs#L180-L181
https://github.com/near/read-rpc/blob/ac8f4f221afe391c20144cd7c7397868d13a525c/rpc-server/src/modules/receipts/methods.rs#L39-L44

2024-06-03 06:13 UTC, kobayurii requested changes
Thank you! Great job! I left a little comment. Also, I noticed that you created a pull request in the main branch.  Please reopen the pull request for the develop branch. `develop` is the main branch for development. Also don't forget to fix the checker.

2024-06-03 07:33 UTC, khorolets commented
> However, I still don't know if it's fine to return non Response type from RPC endpoint. Can someone tell me if it's a good practice:
> 
> https://github.com/near/read-rpc/blob/ac8f4f221afe391c20144cd7c7397868d13a525c/readnode-primitives/src/lib.rs#L180-L181
> 
> 
> https://github.com/near/read-rpc/blob/ac8f4f221afe391c20144cd7c7397868d13a525c/rpc-server/src/modules/receipts/methods.rs#L39-L44

While it's not perfect either, I would suggest following what @kobayurii did for the other custom method we have here 

https://github.com/near/read-rpc/blob/develop/rpc-server/src/modules/state/mod.rs

I am not a fan of duplicating structures, but I would ask you to have the `Resuest/Response` structures defined in the `modules/receipts/mod.rs`

Feel free to implement `From<ReceiptRecord>` or `TryFrom` for your request/response structures. And drop the serde derives from the original structure.

My thoughts come from the idea of having dedicated structures for (again) request/response. Having `From` or `TryFrom` from the internal structure would alert us if we change something in the future.

Thank you for drawing my attention to this question 🙏

2024-06-03 08:16 UTC, khorolets commented
@frolvanya and please update https://github.com/near/read-rpc/blob/main/docs/CUSTOM_RPC_METHODS.md with info about the new method you've added. Thank you.

2024-06-03 15:46 UTC, khorolets approved these changes
Perfect! Thank you 🙏

2024-06-03 15:48 UTC, merged