fix: clarified Redis connection errors and added Redis dependency to docker-compose files
near/read-rpc pull request #278
Opened 2024-06-10 00:39 UTC by frolvanya

- [x] Improve the error to make it less ambiguous, we need a clear message identifying it is related to connection to Redis

  Before: 
  <img width="591" alt="image" src="https://github.com/near/read-rpc/assets/59515280/4f1a963f-5139-4591-9475-b563463f34bb">

  After:
  <img width="785" alt="image" src="https://github.com/near/read-rpc/assets/59515280/ec3e4446-3ef3-4639-926e-bb552e0fa647">

- [x] Update the docker-compose.yml to ensure it is always in a working condition to docker-compose up from main

  To complete this, I've added redis dependency to postgres and rightsizing docker-compose files

- [ ] Decide how to proceed with having Redis as a mandatory dependency and whether the `rpc-server` can work without it even with limited capabilities

  In any case we can merge these minor fixes now and later (@kobayurii @khorolets) will decide wether Redis is required or not

closes #274

2024-06-10 05:24 UTC, khorolets approved these changes
Looks great! I will follow up in a separate issue about decision to transform the Redis dependency to optional

2024-06-10 07:26 UTC, kobayurii requested changes
Hello! Thank you! I think we should use radis for development. It will only be used if we have a running instance of near_state_indexer which is based on nearcore. I would like you to check at the initialization stage whether the connection to redis is established and if there is an error then do not spawn the tasks `update_final_block_regularly_from_redis` and `update_optimistic_block_regularly` and `OPTIMISTIC_UPDATING.set_not_working()`
and generated a Warning error. 
This way you won't have to carry dependencies in all places.

2024-06-10 17:24 UTC, frolvanya commented
> I would also like you to update the `readme.md` specify redis as an optional dependency and describe its use only when paired with near_state_indexer.

Should it be done in main README.md file or inside the rpc-server/README.md?

2024-06-11 06:02 UTC, khorolets commented
> Should it be done in root `README.md` file or inside the `rpc-server/README.md`?

It's enough for now, we'll perform docs cleaning later.

2024-06-11 07:05 UTC, kobayurii approved these changes
Looks good! Thank you!

2024-06-11 07:14 UTC, merged