Database new
near/read-rpc pull request #282
Opened 2024-06-21 10:30 UTC by kobayurii

2024-07-09 13:54 UTC, kobayurii commented
@race-of-sloths please, include my PR in the Race

2024-07-09 13:55 UTC, race-of-sloths commented
@kobayurii Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
New Sloth joined the Race! Welcome!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/kobayurii?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/kobayurii?type=bot&theme=light">
    <img alt="Shows profile picture for the author of the PR" src="https://badge.race-of-sloths.com/kobayurii?type=bot&theme=white">
</picture>](https://race-of-sloths.com/profile/kobayurii)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/kobayurii)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

2024-07-09 18:22 UTC, frolvanya approved these changes

2024-07-10 11:42 UTC, khorolets requested changes
That's a lot of work! Awesome work! I left comments at all the places that caught my eye. Please, point me to any specific parts you would like my extra attention.

2024-07-10 11:42 UTC, khorolets commented on database/src/postgres/rpc_server.rs
> +        let futures = self.shards_pool.iter().map(|(shard_id, pool)| {
Please comment here about our chosen approach: send a query to all shards, expecting only one to result in data.

2024-07-10 11:42 UTC, khorolets commented on database/src/postgres/state_indexer.rs
> +                    .ok_or(anyhow::anyhow!("Shard not found"))?,
In such error messages would be great to include the shard id we tried to simplify the debugging

2024-07-10 11:42 UTC, khorolets commented on rpc-server/src/modules/queries/methods.rs
> +        // TODO: review this once we implement the `account_access_keys` after the redesign
It is time to have a look at this TODO I guess :)

2024-07-10 11:42 UTC, khorolets commented
@race-of-sloths score 13

2024-07-10 11:43 UTC, race-of-sloths commented
### 🌟 Score recorded!

@khorolets, thank you for scoring this pull request in the Race of Sloths!

2024-07-11 09:19 UTC, kobayurii commented on database/src/postgres/mod.rs
> +#[derive(borsh::BorshSerialize, borsh::BorshDeserialize, Clone, Debug)]
we serialize this struct into `bytes` and do `hex:encode` to get `next_page token` to fetch state by pages.

2024-07-15 17:33 UTC, frolvanya commented
@kobayurii Did the the latest commit fix an issue with contract calls? Now everything is ready for the load test?

2024-07-15 17:59 UTC, kobayurii commented
> @kobayurii Did the the latest commit fix an issue with contract calls? Now everything is ready for the load test?

Yes, the latest changes have fixed the problem. We are now ready for the test.

2024-09-10 14:43 UTC, race-of-sloths commented
### ❌ PR inactive
This PR has been inactive for two weeks. It's now marked as stale. 
>[!TIP]
If you think it's a mistake, you can restart the bot with `include` command to proceed 🔄

2024-09-13 20:20 UTC, gilxgil commented
hi @kobayurii we're interested in running this for RPC Nodes, is this planned for main?

2024-09-14 07:26 UTC, kobayurii commented
hi @gilxgil, yes, this will be merged into maine soon, we are doing final testing and debugging. You can try it out here https://v2.rpc.mainnet.near.org

2024-09-16 11:36 UTC, kobayurii commented
@race-of-sloths please, include my PR in the Race

2024-10-09 08:30 UTC, merged